# SOPS 配置文件
# 用于加密 Kubernetes Secrets
keys:
  - &flux age:REPLACE_WITH_YOUR_AGE_PUBLIC_KEY

creation_rules:
  - path_regex: .*/templates/secret.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - REPLACE_WITH_YOUR_AGE_PUBLIC_KEY
