apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <%= projectId %>
  labels:
    project-name: <%= projectName %>
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - <%= projectName %>.juanie.art
    secretName: <%= projectId %>-tls
  rules:
  - host: <%= projectName %>.juanie.art
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: <%= projectId %>
            port:
              number: 80
