apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: !!str <%= projectName %>
  labels:
    app: !!str <%= projectName %>
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - <%= projectName %>.example.com
    secretName: <%= projectName %>-tls
  rules:
  - host: <%= projectName %>.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: !!str <%= projectName %>
            port:
              number: 80
