apiVersion: 1

datasources:
  # Prometheus - 指标数据源
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST

  # Jaeger - 分布式追踪
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['trace_id']

  # Loki - 日志聚合（可选）
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: 'jaeger'
          matcherRegex: 'trace_id=(\w+)'
          name: 'TraceID'
          url: '$${__value.raw}'

  # PostgreSQL - 数据库查询
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: ${POSTGRES_DB:-devops}
    user: ${POSTGRES_USER:-postgres}
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-password}
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
    editable: true
