apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-web
  namespace: {{ .Values.app.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/managed-by: juanie
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}-web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
