apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: juanie-wildcard-tls
  namespace: juanie
spec:
  secretName: juanie-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.juanie.art"
