apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: shared-gateway
  namespace: juanie
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    io.cilium/lb-ipam-ips: "10.2.0.15"
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.juanie.art"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.juanie.art"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: juanie-wildcard-tls
            group: ""
            kind: Secret
