apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: juanie
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    strategy: Setters
    path: ./deploy/flux/charts/juanie
  git:
    commit:
      author:
        email: flux-bot@users.noreply.github.com
        name: flux-bot
      messageTemplate: |
        chore: 自动更新镜像 tag
        {{ range .Changed.Images -}}
        - {{.}}
        {{ end -}}
