apiVersion: v1
kind: Service
metadata:
  name: ai-platform
  namespace: juanie-platform
  labels:
    app: ai-platform
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3002
      protocol: TCP
      name: http
    - port: 9466
      targetPort: 9466
      protocol: TCP
      name: metrics
  selector:
    app: ai-platform
