apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@juanie.art
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          webhook:
            groupName: acme.dnspod.com
            solverName: dnspod
            config:
              secretIdRef:
                name: dnspod-secret
                key: secretId
              secretKeyRef:
                name: dnspod-secret
                key: secretKey
              ttl: 600
