apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}-tls
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Chart.Name }}-tls
  dnsNames:
    - {{ .Values.hostname }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  renewBefore: 360h
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 256
