apiVersion: apps/v1
kind: Deployment
metadata:
  name: <%= projectName %>
spec:
  replicas: 1  # 始终运行
  template:
    spec:
      containers:
      - name: <%= projectName %>
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
