apiVersion: apps/v1
kind: Deployment
metadata:
  name: <%= projectName %>
spec:
  replicas: 1  # 改为 1，方便测试
  template:
    spec:
      containers:
      - name: <%= projectName %>
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
