apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-<%= projectId %>

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: <%= projectId %>

namePrefix: dev-
