apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-<%= projectId %>-development

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: !!str <%= projectName %>

namePrefix: dev-
